use once_cell::sync::Lazy;
use std::collections::HashSet;

/// Tiếng Việt (Vietnamese)
pub static STOPWORDS_VIE: Lazy<HashSet<&'static str>> = Lazy::new(|| {
    [
        "a ha",
        "a-lô",
        "ai ai",
        "ai nấy",
        "ai",
        "alô",
        "amen",
        "anh",
        "bao giờ",
        "bao lâu",
        "bao nhiêu",
        "bao nả",
        "bay biến",
        "biết bao nhiêu",
        "biết bao",
        "biết chừng nào",
        "biết mấy",
        "biết đâu chừng",
        "biết đâu đấy",
        "biết đâu",
        "biết",
        "bà",
        "bài",
        "bác",
        "bây bẩy",
        "bây chừ",
        "bây giờ",
        "bây nhiêu",
        "bèn",
        "béng",
        "bông",
        "bạn",
        "bản",
        "bất chợt",
        "bất cứ",
        "bất giác",
        "bất kì",
        "bất kể",
        "bất kỳ",
        "bất luận",
        "bất nhược",
        "bất quá",
        "bất thình lình",
        "bất tử",
        "bất đồ",
        "bấy chầy",
        "bấy chừ",
        "bấy giờ",
        "bấy lâu nay",
        "bấy lâu",
        "bấy nay",
        "bấy nhiêu",
        "bấy",
        "bập bà bập bõm",
        "bập bõm",
        "bắt đầu từ",
        "bằng không",
        "bằng nấy",
        "bằng ấy",
        "bằng",
        "bển",
        "bệt",
        "bị",
        "bỏ mẹ",
        "bỗng chốc",
        "bỗng dưng",
        "bỗng không",
        "bỗng nhiên",
        "bỗng đâu",
        "bỗng",
        "bộ",
        "bội phần",
        "bớ",
        "bởi chưng",
        "bởi nhưng",
        "bởi thế",
        "bởi vì",
        "bởi vậy",
        "bởi",
        "bức",
        "cao",
        "cha chả",
        "cha",
        "chao ôi",
        "chiếc",
        "cho nên",
        "cho tới khi",
        "cho tới",
        "cho đến khi",
        "cho đến",
        "cho",
        "choa",
        "chu cha",
        "chui cha",
        "chung cục",
        "chung qui",
        "chung quy lại",
        "chung quy",
        "chuyện",
        "chành chạnh",
        "chí chết",
        "chính là",
        "chính thị",
        "chính",
        "chùn chùn",
        "chùn chũn",
        "chú mày",
        "chú mình",
        "chú",
        "chúng mình",
        "chúng ta",
        "chúng tôi",
        "chăn chắn",
        "chăng",
        "chưa",
        "chầm chập",
        "chậc",
        "chắc hẳn",
        "chắc",
        "chẳng lẽ",
        "chẳng những",
        "chẳng nữa",
        "chẳng phải",
        "chết nỗi",
        "chết thật",
        "chết tiệt",
        "chỉ",
        "chỉn",
        "chốc chốc",
        "chớ chi",
        "chớ",
        "chợt",
        "chủn",
        "chứ lị",
        "chứ",
        "coi bộ",
        "coi mòi",
        "con",
        "cu cậu",
        "cuốn",
        "cuộc",
        "càng",
        "các",
        "cái",
        "cây",
        "còn",
        "có chăng là",
        "có dễ",
        "có thể",
        "có vẻ",
        "có",
        "cóc khô",
        "cô mình",
        "cô",
        "công nhiên",
        "cùng cực",
        "cùng nhau",
        "cùng với",
        "cùng",
        "căn cắt",
        "căn",
        "cũng như",
        "cũng vậy thôi",
        "cũng vậy",
        "cũng",
        "cơ chừng",
        "cơ hồ",
        "cơ mà",
        "cơ",
        "cơn",
        "cả thảy",
        "cả thể",
        "cả",
        "cảm ơn",
        "cần",
        "cật lực",
        "cật sức",
        "cậu",
        "cổ lai",
        "của",
        "cứ việc",
        "cứ",
        "cực lực",
        "do vì",
        "do vậy",
        "do đó",
        "do",
        "duy",
        "dào",
        "dì",
        "dù cho",
        "dù rằng",
        "dưới",
        "dạ",
        "dần dà",
        "dần dần",
        "dầu sao",
        "dẫu sao",
        "dẫu",
        "dễ sợ",
        "dễ thường",
        "dở chừng",
        "dữ",
        "em",
        "giữa",
        "gì",
        "hay",
        "hoàn toàn",
        "hoặc",
        "hơn",
        "hầu hết",
        "họ",
        "hỏi",
        "khi",
        "khác",
        "không",
        "luôn",
        "là",
        "làm",
        "lên",
        "lúc",
        "lại",
        "lần",
        "lớn",
        "muốn",
        "mà",
        "mình",
        "mỗi",
        "một cách",
        "một",
        "mới",
        "mợ",
        "ngay cả",
        "ngay khi",
        "ngay lúc",
        "ngay lập tức",
        "ngay tức khắc",
        "ngay từ",
        "ngay",
        "nghe chừng",
        "nghe đâu",
        "nghen",
        "nghiễm nhiên",
        "nghỉm",
        "ngoài ra",
        "ngoài",
        "ngoải",
        "ngày càng",
        "ngày ngày",
        "ngày xưa",
        "ngày xửa",
        "ngày",
        "ngôi",
        "ngõ hầu",
        "ngăn ngắt",
        "ngươi",
        "người",
        "ngọn",
        "ngọt",
        "ngộ nhỡ",
        "nh",
        "nhau",
        "nhiên hậu",
        "nhiều",
        "nhiệt liệt",
        "nhung nhăng",
        "nhà",
        "nhân dịp",
        "nhân tiện",
        "nhé",
        "nhón nhén",
        "như chơi",
        "như không",
        "như quả",
        "như thể",
        "như tuồng",
        "như vậy",
        "như",
        "nhưng mà",
        "nhưng",
        "nhược bằng",
        "nhất loạt",
        "nhất luật",
        "nhất mực",
        "nhất nhất",
        "nhất quyết",
        "nhất sinh",
        "nhất thiết",
        "nhất tâm",
        "nhất tề",
        "nhất đán",
        "nhất định",
        "nhất",
        "nhận",
        "nhỉ",
        "nhỡ ra",
        "những ai",
        "những như",
        "những",
        "nào",
        "này",
        "nên chi",
        "nên",
        "nó",
        "nóc",
        "nói",
        "năm",
        "nơi",
        "nấy",
        "nếu như",
        "nếu",
        "nền",
        "nọ",
        "nớ",
        "nức nở",
        "nữa",
        "oai oái",
        "oái",
        "pho",
        "phè",
        "phóc",
        "phót",
        "phăn phắt",
        "phương chi",
        "phải chi",
        "phải chăng",
        "phải",
        "phắt",
        "phỉ phui",
        "phỏng như",
        "phỏng",
        "phốc",
        "phụt",
        "phứt",
        "qua quít",
        "qua quýt",
        "qua",
        "quyết nhiên",
        "quyết",
        "quyển",
        "quá chừng",
        "quá lắm",
        "quá sá",
        "quá thể",
        "quá trời",
        "quá xá",
        "quá đỗi",
        "quá độ",
        "quá ư",
        "quá",
        "quý hồ",
        "quả là",
        "quả tang",
        "quả thật",
        "quả tình",
        "quả vậy",
        "quả đúng",
        "quả",
        "ra phết",
        "ra sao",
        "ra trò",
        "ra",
        "ren rén",
        "riu ríu",
        "riêng",
        "riệt",
        "rày",
        "ráo trọi",
        "ráo",
        "rén",
        "rích",
        "rón rén",
        "rút cục",
        "răng",
        "rất",
        "rằng là",
        "rằng",
        "rốt cuộc",
        "rốt cục",
        "rồi",
        "rứa",
        "sa sả",
        "sao",
        "sau chót",
        "sau cuối",
        "sau cùng",
        "sau đó",
        "sau",
        "so",
        "song le",
        "suýt",
        "sì",
        "sạch",
        "sất",
        "sắp",
        "sẽ",
        "số là",
        "số",
        "sốt sột",
        "sở dĩ",
        "sự",
        "tanh",
        "tha hồ",
        "than ôi",
        "thanh",
        "theo",
        "thi thoảng",
        "thoạt nhiên",
        "thoạt",
        "thoắt",
        "thuần",
        "thà là",
        "thà rằng",
        "thà",
        "thành ra",
        "thành thử",
        "thái quá",
        "tháng",
        "thì thôi",
        "thì",
        "thình lình",
        "thím",
        "thôi",
        "thúng thắng",
        "thương ôi",
        "thường",
        "thảo hèn",
        "thảo nào",
        "thấy",
        "thẩy",
        "thậm chí",
        "thậm",
        "thật lực",
        "thật ra",
        "thật vậy",
        "thế là",
        "thế mà",
        "thế nào",
        "thế nên",
        "thế ra",
        "thế thì",
        "thế à",
        "thế",
        "thếch",
        "thỉnh thoảng",
        "thỏm",
        "thốc tháo",
        "thốc",
        "thốt nhiên",
        "thốt",
        "thộc",
        "thời gian",
        "thục mạng",
        "thửa",
        "thực ra",
        "thực sự",
        "thực vậy",
        "tiếp theo",
        "tiếp đó",
        "tiện thể",
        "toà",
        "toé khói",
        "toẹt",
        "trong",
        "trên",
        "trước kia",
        "trước nay",
        "trước tiên",
        "trước đây",
        "trước đó",
        "trước",
        "trếu tráo",
        "trển",
        "trệt",
        "trệu trạo",
        "trỏng",
        "trời đất ơi",
        "trừ phi",
        "tuy nhiên",
        "tuy rằng",
        "tuy thế",
        "tuy vậy",
        "tuy",
        "tuyệt nhiên",
        "tuần tự",
        "tuốt luốt",
        "tuốt tuồn tuột",
        "tuốt tuột",
        "tà tà",
        "tênh",
        "tít mù",
        "tò te",
        "tôi",
        "tông tốc",
        "tù tì",
        "tăm tắp",
        "tại vì",
        "tại",
        "tấm",
        "tấn",
        "tất cả",
        "tất thảy",
        "tất tần tật",
        "tất tật",
        "tắp lự",
        "tắp",
        "tọt",
        "tỏ ra",
        "tỏ vẻ",
        "tốc tả",
        "tối ư",
        "tột",
        "tớ",
        "tới",
        "tức thì",
        "tức tốc",
        "từ",
        "từng",
        "tự vì",
        "tựu trung",
        "veo veo",
        "veo",
        "việc",
        "vung thiên địa",
        "vung tàn tán",
        "vung tán tàn",
        "và",
        "vào",
        "vâng",
        "vèo",
        "vì chưng",
        "vì thế",
        "vì vậy",
        "vì",
        "ví bằng",
        "ví dù",
        "ví phỏng",
        "ví thử",
        "vô hình trung",
        "vô kể",
        "vô luận",
        "vô vàn",
        "văng tê",
        "vạn nhất",
        "vả chăng",
        "vả lại",
        "vẫn",
        "vậy là",
        "vậy thì",
        "vậy",
        "về",
        "vị tất",
        "vốn dĩ",
        "với lại",
        "với",
        "vở",
        "vụt",
        "vừa mới",
        "vừa",
        "xa xả",
        "xiết bao",
        "xon xón",
        "xoành xoạch",
        "xoét",
        "xoẳn",
        "xoẹt",
        "xuất kì bất ý",
        "xuất kỳ bất ý",
        "xuể",
        "xuống",
        "xăm xúi",
        "xăm xăm",
        "xăm xắm",
        "xềnh xệch",
        "xệp",
        "à ơi",
        "à",
        "ào",
        "á à",
        "á",
        "ái chà",
        "ái dà",
        "ái",
        "áng",
        "âu là",
        "ô hay",
        "ô hô",
        "ô kê",
        "ô kìa",
        "ôi chao",
        "ôi thôi",
        "ông",
        "úi chà",
        "úi dào",
        "úi",
        "ý chừng",
        "ý da",
        "ý",
        "đang",
        "đi",
        "điều",
        "đành đạch",
        "đáng lí",
        "đáng lý",
        "đáng lẽ",
        "đánh đùng",
        "đáo để",
        "đây",
        "đã",
        "đó",
        "được",
        "đại loại",
        "đại nhân",
        "đại phàm",
        "đại để",
        "đến nỗi",
        "đến",
        "đều",
        "để",
        "ơ hay",
        "ơ kìa",
        "ơ",
        "ơi",
        "ư",
        "ạ ơi",
        "ạ",
        "ấy",
        "ầu ơ",
        "ắt hẳn",
        "ắt là",
        "ắt",
        "ối dào",
        "ối giời ơi",
        "ối giời",
        "ồ",
        "ổng",
        "ớ",
        "ờ",
        "ở trên",
        "ở",
        "ủa",
        "ứ hự",
        "ứ ừ",
        "ừ",
        "ử",
    ]
    .iter()
    .cloned()
    .collect()
});
